# Site settings
title: Schettino's thoughts
email: bpschettino@gmail.com
description: Just my thoughts about things

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bschettino.github.io" # the base hostname & protocol for your site
paginate_path: "blog/page:num/"
permalink: blog/:title/

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: bschettino
   twitter: bschettino
   facebook: bpschettino
   email: bpschettino@gmail.com

# Build settings
markdown: redcarpet
highlighter: pygments
paginate: 5

google_analytics: ""